# Generated by Django 4.2.5 on 2023-09-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_alter_customuser_groups_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
