# Generated by Django 4.2.5 on 2023-09-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='data_json',
            field=models.JSONField(default=dict),
        ),
    ]
