# Generated by Django 4.2.5 on 2023-09-21 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='received_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlet.product'),
        ),
        migrations.AddField(
            model_name='master',
            name='received_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
