# Generated by Django 4.2.5 on 2023-09-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
