# Generated by Django 4.2.5 on 2023-09-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0003_productindex_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindex',
            name='available_quantity',
        ),
    ]
