# Generated by Django 4.2.5 on 2023-09-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0004_remove_productindex_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='batch_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
