# Generated by Django 4.2.5 on 2023-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0006_productindex_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='data_json',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead')], default='in_progress', max_length=20),
        ),
    ]
