# Generated by Django 4.2.6 on 2023-10-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0007_alter_master_data_json_alter_master_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead')], default='in_progress', max_length=20),
        ),
    ]
