# Generated by Django 4.2.6 on 2023-10-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0008_alter_productindex_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
