# Generated by Django 4.2.6 on 2023-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0009_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_gstin',
            field=models.CharField(default='00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='UOM',
            field=models.CharField(default='soc', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='ammount',
            field=models.PositiveIntegerField(default='000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='gate_inward_No',
            field=models.CharField(default='111', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='part_bill_no',
            field=models.PositiveIntegerField(default='000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='part_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='party_challan_no',
            field=models.PositiveIntegerField(default='0001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='po_no',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='rate',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
