# Generated by Django 4.2.6 on 2023-10-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0010_product_supplier_gstin_productindex_uom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
