# Generated by Django 4.2.6 on 2023-10-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inlet', '0009_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complet', 'Complete')], default='pending', max_length=20)),
                ('grn_number', models.CharField(max_length=50)),
                ('po_number', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('uuids', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complet', 'Complete')], default='pending', max_length=20)),
                ('uuids', models.JSONField(blank=True, default=list, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlet.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.saleorder')),
            ],
        ),
        migrations.AddField(
            model_name='saleorder',
            name='products',
            field=models.ManyToManyField(through='outlet.SaleOrderProduct', to='inlet.product'),
        ),
    ]
