# Generated by Django 4.2.6 on 2023-10-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inlet', '0008_alter_productindex_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=50)),
                ('po_number', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlet.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.saleorder')),
            ],
        ),
        migrations.AddField(
            model_name='saleorder',
            name='products',
            field=models.ManyToManyField(through='outlet.SaleOrderProduct', to='inlet.product'),
        ),
    ]
