# Generated by Django 4.2.6 on 2023-10-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
